module.exports.places = [
    'Hollow',
    'Cliffs',
    'Hunting Camp',
    'Mule Camp',
    'Sands',
    'Bayshore',
    'Spring',
    'Bay',
    'Creek',
    'Creekside',
    'River',
    'Backcountry',
    'Dispersed Camp',
    'Camp',
    'Ghost Town',
    'Horse Camp',
    'Group Camp',
    'Pond',
    'Canyon',
    'Village',
    'Flats',
    'Death Valley',
    'Mountain Pass',
    'Red Cliff',
    'Snake River',
    'Alcatraz',
    'Bellow Woods',
    'Blood Strip'
];

module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sky',
    'Sea',
    'Dusty',
    'Diamond',
    'Deadmans',
    'Weeping Hollow',
    'Ragnarok',
    'Oasis',
    'Dark',
    'Haunted',
    'Eragon',
];